j_rep: 0 # 周期境界条件 0:周期境界条件無 1:周期境界条件

lam : 3.0 # 水路の波長(m)
nx0 : 41 # 格子数/1波長
ny : 21 # 横断方向格子数(奇数推奨)
wn : 2 # 波数
chb : 0.4 # 水路幅(m)
t0_degree : 40 # 最大蛇行偏角(Degree)
slope: 0.001 # 水路勾配
xsize: 20 # 計算結果をプロットする図の横スケール


amp : 0.015 # 初期河床砂州の波高(m)
delta : 0.2 # 初期河床砂州の位相差(m)
beta_0: 0. # 内岸で川幅を狭める割合
amp_0: 0.0 # 狭めた部分の河床高さ(m)

snu_0 : 1e-6 # 動粘性係数
hmin : 0.001 # 最小水深(m)
cw: 0.001 # 側壁摩擦係数
ep_alpha: 1. # 渦動粘性係数の係数

qp: 0.001 # 流量(m^3/s)
snm: 0.012 # マニング粗度
g: 9.8 # 重力加速度(m/s^2)

j_west: 0 # 上流条件(0:開放, 1:閉鎖)
j_east: 0 # 下流条件(0:開放, 1:閉鎖)
j_hdown: 1 # 下流端水位条件(0:自由流出, 1:等流水深, 2:固定水位を与える)
h_down : 1. # j_hdown=2 の時の固定水位(m)
j_inih: 2 #初期水位縦断 0:直線 1:等流計算 2:不等流計算

alh: 0.6 # 水位収束計算のReluxsation係数
lmax: 20 # 各タイムステップでの水位収束計算最大回数

etime: 60. # 計算終了時間(sec)
tuk: 1.0 # 計算結果アウトプット間隔(sec)
dt: 0.002 # 計算タイムステップ(sec)
stime: 0. # アウトプット開始時間(sec)

j_obst: 0 # 障害物の有無 0=無 1=有
jo_type: 2 # 障害物設置方法 1=ファイルから読む 2=条件を指定する
jo_method: 4 # 0=無 1=右岸のみ 2=左岸のみ 3=左右岸(千鳥) 4=左右岸(同位置)
f_dike_pos: 0.8 # 最初の水制の位置(m)
dike_dis: 0.8 # 水制間隔(m)
dike_length: 0.1 # 水制長(m)
dike_thick: 0.02 # 水制厚(m)
num_dike : 3 # 水制本数(方岸当たり)

iskip: 1 # ベクトルプロットの i 方向間引き
jskip: 1 # ベクトルプロットの j 方向間引き
jscale: 15 # ベクトルのスケールファクター

alpha_upu : 0.05 # 周期境界条件の緩和係数

vcolor : yellow # ベクトルのカラー
rrmax: 25 # 曲率プロットの軸最大値(1/m)
